# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target ‘hhru’ do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # ignore all warnings from all pods
  inhibit_all_warnings!

  # Pods for Booze
  pod 'Alamofire', '4.5.1'
  pod 'AlamofireImage', '3.3.0'
  pod 'SwiftyJSON', '3.1.4'
  pod 'PKHUD', '5.0'
end
